### ISSUE TITLE
Can you provide a grey Orange theme

### ISSUE THREAD

**Issue by jahnli** [niccolomineo/vscode-nights-theme#1]
Can you provide a grey Orange theme
[grey_orange.zip](https://github.com/niccolomineo/vscode-nights-theme/files/5382186/grey_orange.zip)

**Comment by niccolomineo** [comment]
Hi, can you attach a screenshot of what you exactly mean?

Thank you.

**Comment by jahnli** [comment]
May I ask if the webStorm theme is converted to the vSCode theme

**Comment by jahnli** [comment]
Could you help me switch a topic and I can make a donation

**Comment by niccolomineo** [comment]
> May I ask if the webStorm theme is converted to the vSCode theme

I took two VSCode themes inspired by IntelliJ and mixed them together. The result is a theme that is for VSCode.

**Comment by niccolomineo** [comment]
> Could you help me switch a topic and I can make a donation

Sorry, I do not understand what you are talking about here.

**Comment by jahnli** [comment]
If you can help me make it, I'll pay for it
